// Common constants used across the application

export const BANKS = [
  "State Bank of India", "HDFC Bank", "ICICI Bank", "Axis Bank", "Kotak Mahindra Bank",
  "Punjab National Bank", "Bank of Baroda", "Yes Bank", "IndusInd Bank", "Union Bank of India",
  "Canara Bank", "Central Bank of India", "Bank of India", "Indian Bank", "Bank of Maharashtra",
  "UCO Bank", "Indian Overseas Bank", "Oriental Bank of Commerce", "Allahabad Bank", "Syndicate Bank",
  "Corporation Bank", "Dena Bank", "Andhra Bank", "Bharat Bank", "Central Bank of India",
  "Indian Bank", "Indian Overseas Bank", "Punjab & Sind Bank", "United Bank of India", "South Indian Bank",
  "Tamilnad Mercantile Bank", "Karur Vysya Bank", "Lakshmi Vilas Bank", "City Union Bank", "Federal Bank",
  "DCB Bank", "RBL Bank", "IDFC FIRST Bank", "Bandhan Bank", "AU Small Finance Bank", "ESAF Small Finance Bank",
  "Jana Small Finance Bank", "Equitas Small Finance Bank", "Suryoday Small Finance Bank", "Fincare Small Finance Bank"
];

export const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

export const DESIGNATIONS = [
  // Interns & Junior Roles
  "Software Intern",
  "Trainee Software Engineer",
  "Associate Software Engineer",
  "Junior Software Developer",
  "Junior Java Developer",
  "Junior Python Developer",
  "Junior Frontend Developer",
  "Junior Backend Developer",
  "Junior Full Stack Developer",
  "Junior Web Developer",
  "Junior API Developer",
  "Junior Mobile Developer",
  "Junior React Developer",
  "Junior Node.js Developer",
  "Junior Angular Developer",
  "Junior .NET Developer",
  "Junior PHP Developer",
  "Junior Database Developer",
  "Junior Salesforce Developer",
  "Junior Cloud Engineer",
  "Junior DevOps Engineer",
  "Junior QA Engineer",
  "Junior Manual Tester",
  "Junior Automation Tester",
  "Junior Data Analyst",
  "Junior Machine Learning Engineer",
  "Junior Data Engineer",
  "Junior Network Engineer",
  "Junior IT Support Engineer",
  "Junior Security Analyst",

  // Core Software Roles
  "Software Developer",
  "Software Engineer",
  "Web Developer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "API Developer",
  "Java Developer",
  "Python Developer",
  "Node.js Developer",
  "React.js Developer",
  "Angular Developer",
  "Vue.js Developer",
  "PHP Developer",
  ".NET Developer",
  "Android Developer",
  "iOS Developer",
  "Flutter Developer",
  "React Native Developer",
  "Mobile App Developer",

  // Cloud & DevOps
  "Cloud Engineer",
  "AWS Cloud Engineer",
  "Azure Cloud Engineer",
  "GCP Cloud Engineer",
  "Cloud Support Associate",
  "AWS Solutions Architect Associate",
  "AWS DevOps Engineer",
  "Cloud Security Engineer",
  "Cloud Operations Engineer",
  "Cloud Migration Specialist",
  "DevOps Engineer",
  "Build and Release Engineer",
  "Infrastructure Engineer",
  "CI/CD Engineer",
  "Docker Specialist",
  "Kubernetes Engineer",
  "Site Reliability Engineer (SRE)",
  "Automation Engineer",
  "Linux Systems Engineer",
  "Configuration Management Engineer",

  // QA & Testing
  "Manual Tester",
  "Automation Tester",
  "QA Engineer",
  "Quality Assurance Engineer",
  "Test Analyst",
  "Performance Tester",
  "Security Tester",
  "Software Test Engineer",
  "UAT Tester",
  "QA Automation Engineer",

  // Salesforce & CRM
  "Salesforce Administrator",
  "Salesforce Developer",
  "Salesforce Consultant",
  "Salesforce Business Analyst",
  "Salesforce Data Specialist",
  "Salesforce Integration Specialist",
  "Salesforce Marketing Cloud Specialist",
  "Salesforce Functional Consultant",
  "CRM Developer",
  "CRM Functional Consultant",

  // Data & AI
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "NLP Engineer",
  "Deep Learning Engineer",
  "Computer Vision Engineer",
  "Data Engineer",
  "Big Data Engineer",
  "Business Intelligence Developer",
  "Database Administrator (DBA)",
  "SQL Developer",
  "PostgreSQL Developer",
  "MySQL Developer",
  "MongoDB Developer",
  "ETL Developer",
  "NoSQL Developer",
  "Data Warehouse Engineer",
  "Database Analyst",
  "Database Developer",

  // Project & Product
  "Project Coordinator",
  "Project Associate",
  "Business Analyst",
  "Product Analyst",
  "Scrum Master",
  "Agile Coach",
  "Product Manager",
  "Project Manager (IT)",
  "Program Manager",
  "Delivery Manager",

  // Security & IT Operations
  "Information Security Analyst",
  "Cybersecurity Analyst",
  "Penetration Tester",
  "Ethical Hacker",
  "SOC Analyst",
  "Network Engineer",
  "Systems Administrator",
  "IT Support Engineer",
  "Infrastructure Support Engineer",
  "IT Operations Engineer",

  // Support & Enablement
  "Technical Writer",
  "Documentation Specialist",
  "ERP Functional Consultant",
  "Implementation Engineer",
  "Solution Consultant",
  "Technical Support Engineer",
  "Customer Success Engineer",
  "IT Trainer",
  "IT Auditor",
  "Business Consultant",

  // Senior & Lead Roles
  "Senior Software Developer",
  "Senior Software Engineer",
  "Senior Java Developer",
  "Senior Python Developer",
  "Senior Full Stack Developer",
  "Senior Frontend Engineer",
  "Senior Backend Engineer",
  "Senior React Developer",
  "Senior Node.js Developer",
  "Senior Web Developer",
  "Senior Cloud Engineer",
  "Senior AWS Engineer",
  "Senior Azure Engineer",
  "Senior Cloud Consultant",
  "Senior DevOps Engineer",
  "Senior Infrastructure Engineer",
  "Senior Site Reliability Engineer",
  "Senior Database Administrator",
  "Senior Data Engineer",
  "Senior QA Engineer",
  "Senior Automation Tester",
  "Senior Salesforce Developer",
  "Senior Data Scientist",
  "Senior Machine Learning Engineer",
  "Senior AI Engineer",
  "Senior Business Analyst",
  "Senior Project Manager",
  "Senior Product Manager",
  "Senior Network Engineer",
  "Senior Cybersecurity Engineer",

  // Leads
  "Module Lead",
  "Technical Lead",
  "Development Lead",
  "QA Lead",
  "Test Lead",
  "Data Lead",
  "Cloud Lead",
  "DevOps Lead",
  "Salesforce Lead",
  "Product Lead",

  // Architecture
  "Software Architect",
  "Solution Architect",
  "Application Architect",
  "Technical Architect",
  "Cloud Architect",
  "DevOps Architect",
  "Data Architect",
  "AI/ML Architect",
  "Database Architect",
  "Salesforce Architect",

  // Management & Leadership
  "Software Development Manager",
  "Project Manager",
  "Product Owner",
  "Delivery Manager",
  "QA Manager",
  "DevOps Manager",
  "Cloud Operations Manager",
  "Data Science Manager",
  "IT Operations Manager",
  "Security Manager",
  "Engineering Manager",
  "Senior Engineering Manager",
  "Director of Engineering",
  "Director of Software Development",
  "Director of Cloud Engineering",
  "Director of DevOps",
  "Director of Data Science",
  "Director of Quality Assurance",
  "Director of Technology",
  "Director of Information Security",
  "Head of Engineering",
  "Head of Cloud Operations",
  "Head of DevOps",
  "Head of Data Analytics",
  "Head of Product",
  "Head of IT Operations",
  "Head of Information Security",
  "Head of Salesforce Practice",
  "Head of Project Delivery",
  "Head of Artificial Intelligence",

  // Executive Leadership
  "Vice President – Engineering",
  "Vice President – Cloud",
  "Vice President – DevOps",
  "Vice President – Data Science",
  "Vice President – Quality Assurance",
  "Vice President – IT Operations",
  "Vice President – Product Management",
  "Vice President – Cybersecurity",
  "Vice President – Technology",
  "Vice President – Delivery",
  "Chief Technology Officer (CTO)",
  "Chief Information Officer (CIO)",
  "Chief Digital Officer (CDO)",
  "Chief Information Security Officer (CISO)",
  "Chief Data Officer (CDO – Data)",
  "Chief Product Officer (CPO)",
  "Chief AI Officer",

  // Additional design & platform roles retained
  "UI/UX Designer",
  "UI Designer",
  "UX Designer",
  "Product Designer",
  "Visual Designer",
  "Graphic Designer",
  "Web Designer",
  "Interaction Designer",
  "SDET",
  "Developer Advocate",
  "Enterprise Architect",
  "Business Intelligence Developer",
  "ERP Consultant",
  "SharePoint Developer",
  "WordPress Developer"
];