import React, { useState } from "react";
import { useDispatch } from "react-redux";
import axios from "axios";
import { acceptOffer, rejectOffer } from "../../redux/slices/offerSlice";
import { API_BASE } from "../../utils/apiConfig";
import { toast } from "react-toastify";
import { motion, AnimatePresence } from "framer-motion";
import { FaFilePdf, FaCheck, FaTimes, FaMapMarkerAlt, FaCalendarAlt, FaMoneyBillWave, FaClock } from "react-icons/fa";

const OfferLetterPortal = ({ offer, appointment, candidate, onAction }) => {
  const dispatch = useDispatch();
  const [submitting, setSubmitting] = useState(false);
  const [showAcceptModal, setShowAcceptModal] = useState(false);
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [showAcceptAppModal, setShowAcceptAppModal] = useState(false);
  const [rejectionReason, setRejectionReason] = useState("");

  const handleAcceptAppointment = async () => {
    setSubmitting(true);
    try {
      const token = localStorage.getItem("token");
      const res = await axios.put(`${API_BASE}/api/appointments/candidate/${candidate._id}/accept`, {}, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.data.success) {
        toast.success("Letter of Appointment accepted successfully! Welcome to the team.");
        setShowAcceptAppModal(false);
        if (onAction) onAction();
      }
    } catch (err) {
      console.error(err);
      toast.error(err.response?.data?.error || "Failed to accept appointment letter.");
    } finally {
      setSubmitting(false);
    }
  };

  const formattedSalary = new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0
  }).format(offer?.salaryPackage || 0);

  const formattedJoining = offer?.joiningDate
    ? new Date(offer.joiningDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : "";

  const handleAccept = async () => {
    setSubmitting(true);
    try {
      const resultAction = await dispatch(acceptOffer(offer._id));
      if (acceptOffer.fulfilled.match(resultAction)) {
        toast.success("Offer accepted successfully! Welcome to the team.");
        setShowAcceptModal(false);
        if (onAction) onAction();
      } else {
        toast.error(resultAction.payload || "Failed to accept offer.");
      }
    } catch (err) {
      toast.error("Acceptance failed.");
    } finally {
      setSubmitting(false);
    }
  };

  const handleReject = async () => {
    if (!rejectionReason.trim()) {
      toast.warning("Please provide a reason for rejection.");
      return;
    }

    setSubmitting(true);
    try {
      const resultAction = await dispatch(rejectOffer({ id: offer._id, reason: rejectionReason }));
      if (rejectOffer.fulfilled.match(resultAction)) {
        toast.info("Offer letter rejected. HR will be notified.");
        setShowRejectModal(false);
        if (onAction) onAction();
      } else {
        toast.error(resultAction.payload || "Failed to reject offer.");
      }
    } catch (err) {
      toast.error("Rejection failed.");
    } finally {
      setSubmitting(false);
    }
  };

  if (!offer) {
    return (
      <div className="rounded-3xl border border-white/10 bg-slate-900/40 p-8 text-center backdrop-blur-xl max-w-4xl mx-auto shadow-2xl">
        <FaClock size={40} className="mx-auto text-slate-500 mb-4 animate-pulse" />
        <h3 className="text-xl font-bold">Offer Letter Pending</h3>
        <p className="text-sm text-slate-400 mt-2">
          Your employment offer letter is currently being generated by our HR team. You will receive an email notification once it is ready.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      {/* Summary Header */}
      <div className="rounded-3xl border border-white/10 bg-slate-900/40 p-6 md:p-8 backdrop-blur-xl shadow-2xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <span className="text-xs font-semibold text-blue-500 uppercase tracking-widest">Job Offer Details</span>
            <h3 className="text-2xl font-bold mt-1">{offer.designation}</h3>
            <p className="text-sm text-slate-400 mt-1">Speshway Solutions Private Limited</p>
          </div>

          <div className="flex items-center gap-3">
            <span className={`rounded-full px-3 py-1.5 text-xs font-bold uppercase ${
              offer.status === "Accepted" ? "bg-green-500/10 text-green-400 border border-green-500/20" :
              offer.status === "Sent" ? "bg-blue-500/10 text-blue-400 border border-blue-500/20" :
              offer.status === "Rejected" ? "bg-red-500/10 text-red-400 border border-red-500/20" : "bg-yellow-500/10 text-yellow-400"
            }`}>
              Offer {offer.status}
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mt-8 border-t border-white/5 pt-6">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
              <FaMoneyBillWave /> Annual CTC
            </div>
            <div className="text-lg font-bold text-white">{formattedSalary}</div>
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
              <FaCalendarAlt /> Joining Date
            </div>
            <div className="text-lg font-bold text-white">{formattedJoining}</div>
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
              <FaMapMarkerAlt /> Work Location
            </div>
            <div className="text-lg font-bold text-white">{offer.workLocation}</div>
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
              <FaClock /> Notice Period
            </div>
            <div className="text-lg font-bold text-white">{offer.noticePeriod}</div>
          </div>
        </div>
      </div>

      {/* Main Review Panel */}
      <div className="rounded-3xl border border-white/10 bg-slate-900/40 p-6 md:p-8 backdrop-blur-xl shadow-2xl space-y-6">
        <h4 className="text-lg font-bold">Offer Letter Document</h4>
        
        {/* PDF Download section */}
        {offer.offerLetterUrl && (
          <div className="flex items-center justify-between p-4 rounded-2xl border border-white/5 bg-slate-950/20">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-lg bg-red-500/10 text-red-400"><FaFilePdf size={24} /></div>
              <div>
                <div className="text-sm font-semibold">OfferLetter_{candidate?.candidateId || "CAN"}.pdf</div>
                <div className="text-xs text-slate-500">Official employment document</div>
              </div>
            </div>
            <a
              href={offer.offerLetterUrl.startsWith("http") ? offer.offerLetterUrl : `${API_BASE}${offer.offerLetterUrl}`}
              target="_blank"
              rel="noopener noreferrer"
              className="rounded-xl border border-white/10 hover:bg-white/5 px-4 py-2 text-sm font-bold transition flex items-center gap-2"
            >
              <FaFilePdf /> View & Download PDF
            </a>
          </div>
        )}

        {/* Digital Signature section / Accept & Reject controls */}
        {offer.status === "Sent" && (
          <div className="flex items-center justify-end gap-4 border-t border-white/5 pt-6 mt-6">
            <button
              onClick={() => setShowRejectModal(true)}
              className="rounded-xl border border-red-500/30 text-red-400 hover:bg-red-500/5 px-6 py-3 font-semibold transition flex items-center gap-2"
            >
              <FaTimes /> Decline Offer
            </button>
            <button
              onClick={() => setShowAcceptModal(true)}
              className="rounded-xl bg-blue-600 hover:bg-blue-700 px-6 py-3 font-semibold transition text-white flex items-center gap-2 shadow-lg shadow-blue-500/20"
            >
              <FaCheck /> Accept & Sign Offer
            </button>
          </div>
        )}

        {offer.status === "Accepted" && (
          <div className="rounded-2xl border border-green-500/30 bg-green-950/10 p-5 text-center text-green-400">
            <FaCheck size={30} className="mx-auto mb-2 text-green-500" />
            <div className="text-sm font-bold">You accepted this offer letter on {new Date(offer.acceptanceDate).toLocaleDateString()}.</div>
            <div className="text-xs text-slate-400 mt-1">Your HR representative is preparing your onboarding documents.</div>
          </div>
        )}
      </div>

      {/* Appointment Letter Panel */}
      {appointment && (
        <div className="rounded-3xl border border-white/10 bg-slate-900/40 p-6 md:p-8 backdrop-blur-xl shadow-2xl space-y-6">
          <h4 className="text-lg font-bold text-blue-400">Letter of Appointment</h4>
          
          {/* Appointment details summary */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 p-5 rounded-2xl border border-white/5 bg-slate-950/20">
            <div className="space-y-1">
              <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
                <FaMoneyBillWave /> Annual Package
              </div>
              <div className="text-md font-bold text-white">
                {new Intl.NumberFormat("en-IN", {
                  style: "currency",
                  currency: "INR",
                  maximumFractionDigits: 0
                }).format(appointment.salaryPackage || 0)}
              </div>
            </div>
            <div className="space-y-1">
              <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
                <FaCalendarAlt /> Effective Date
              </div>
              <div className="text-md font-bold text-white">
                {new Date(appointment.joiningDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
              </div>
            </div>
            <div className="space-y-1">
              <div className="flex items-center gap-2 text-slate-400 text-xs font-medium uppercase tracking-wider">
                <FaClock /> Reporting Time
              </div>
              <div className="text-md font-bold text-white">{appointment.reportingTime || "09:00"}</div>
            </div>
          </div>

          {/* Appointment PDF Link */}
          {appointment.appointmentLetterUrl && (
            <div className="flex flex-col sm:flex-row items-center justify-between p-4 rounded-2xl border border-white/5 bg-slate-950/20 gap-4">
              <div className="flex items-center gap-4">
                <div className="p-3 rounded-lg bg-red-500/10 text-red-400"><FaFilePdf size={24} /></div>
                <div>
                  <div className="text-sm font-semibold">AppointmentLetter_{candidate?.candidateId || "CAN"}.pdf</div>
                  <div className="text-xs text-slate-500">Official Letter of Appointment</div>
                </div>
              </div>
              <a
                href={appointment.appointmentLetterUrl.startsWith("http") ? appointment.appointmentLetterUrl : `${API_BASE}${appointment.appointmentLetterUrl}`}
                target="_blank"
                rel="noopener noreferrer"
                className="rounded-xl border border-white/10 hover:bg-white/5 px-4 py-2 text-sm font-bold transition flex items-center gap-2 shrink-0"
              >
                <FaFilePdf /> View & Download PDF
              </a>
            </div>
          )}

          {/* Accept Appointment controls */}
          {appointment.status === "Sent" && (
            <div className="flex items-center justify-end gap-4">
              <button
                onClick={() => setShowAcceptAppModal(true)}
                className="rounded-xl bg-blue-600 hover:bg-blue-700 px-6 py-3 font-semibold transition text-white flex items-center gap-2 shadow-lg shadow-blue-500/20"
              >
                <FaCheck /> Accept & Sign Appointment Letter
              </button>
            </div>
          )}

          {appointment.status === "Accepted" && (
            <div className="rounded-2xl border border-green-500/30 bg-green-950/10 p-5 text-center text-green-400">
              <FaCheck size={30} className="mx-auto mb-2 text-green-500" />
              <div className="text-sm font-bold">You accepted this appointment letter.</div>
              <div className="text-xs text-slate-400 mt-1">Your permanent employee portal access is being finalized by HR.</div>
            </div>
          )}
        </div>
      )}

      {/* Main Container Wrapper Continuation */}
      <div>

        {offer.status === "Rejected" && (
          <div className="rounded-2xl border border-red-500/30 bg-red-950/10 p-5 text-center text-red-400">
            <FaTimes size={30} className="mx-auto mb-2 text-red-500" />
            <div className="text-sm font-bold">You declined this offer letter.</div>
            {offer.rejectionReason && <div className="text-xs text-slate-400 mt-2"><b>Reason:</b> {offer.rejectionReason}</div>}
          </div>
        )}
      </div>

      {/* Confirmation Modals */}
      <AnimatePresence>
        {/* Accept Modal */}
        {showAcceptModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"
            >
              <h3 className="text-lg font-bold text-white mb-2">Accept Job Offer</h3>
              <p className="text-sm text-slate-400 mb-6">
                By accepting, you confirm that you reviewed the salary package and agree to join Speshway Solutions on {formattedJoining}.
              </p>
              <div className="flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setShowAcceptModal(false)}
                  className="rounded-lg border border-white/10 px-4 py-2 text-xs font-semibold text-slate-300 hover:bg-white/5 transition"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleAccept}
                  disabled={submitting}
                  className="rounded-lg bg-blue-600 hover:bg-blue-700 px-4 py-2 text-xs font-semibold text-white transition disabled:opacity-50"
                >
                  {submitting ? "Signing..." : "Confirm & Sign"}
                </button>
              </div>
            </motion.div>
          </div>
        )}

        {/* Reject Modal */}
        {showRejectModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"
            >
              <h3 className="text-lg font-bold text-white mb-2">Decline Offer</h3>
              <p className="text-sm text-slate-400 mb-4">Please let us know your reason for declining this job offer.</p>
              
              <textarea
                className="w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white placeholder-slate-500 outline-none focus:border-red-500 mb-6"
                rows={3}
                placeholder="Reason for declining..."
                value={rejectionReason}
                onChange={(e) => setRejectionReason(e.target.value)}
              />

              <div className="flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setShowRejectModal(false)}
                  className="rounded-lg border border-white/10 px-4 py-2 text-xs font-semibold text-slate-300 hover:bg-white/5 transition"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleReject}
                  disabled={submitting}
                  className="rounded-lg bg-red-600 hover:bg-red-700 px-4 py-2 text-xs font-semibold text-white transition disabled:opacity-50"
                >
                  {submitting ? "Declining..." : "Decline Job Offer"}
                </button>
              </div>
            </motion.div>
          </div>
        )}

        {/* Accept Appointment Modal */}
        {showAcceptAppModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"
            >
              <h3 className="text-lg font-bold text-white mb-2">Accept Appointment Letter</h3>
              <p className="text-sm text-slate-400 mb-6">
                By accepting, you confirm that you reviewed the terms of employment and agree to join Speshway Solutions as a permanent employee.
              </p>
              <div className="flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setShowAcceptAppModal(false)}
                  className="rounded-lg border border-white/10 px-4 py-2 text-xs font-semibold text-slate-300 hover:bg-white/5 transition"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleAcceptAppointment}
                  disabled={submitting}
                  className="rounded-lg bg-blue-600 hover:bg-blue-700 px-4 py-2 text-xs font-semibold text-white transition disabled:opacity-50"
                >
                  {submitting ? "Signing..." : "Confirm & Sign"}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default OfferLetterPortal;
